set(_CATKIN_CURRENT_PACKAGE "julia_project")
set(julia_project_VERSION "1.0.0")
set(julia_project_MAINTAINER "UMD ARC Lab <umdarclab@gmail.com>")
set(julia_project_PACKAGE_FORMAT "1")
set(julia_project_BUILD_DEPENDS )
set(julia_project_BUILD_EXPORT_DEPENDS "baxter")
set(julia_project_BUILDTOOL_DEPENDS "catkin")
set(julia_project_BUILDTOOL_EXPORT_DEPENDS )
set(julia_project_EXEC_DEPENDS "baxter")
set(julia_project_RUN_DEPENDS "baxter")
set(julia_project_TEST_DEPENDS )
set(julia_project_DOC_DEPENDS )
set(julia_project_DEPRECATED "")