set(_CATKIN_CURRENT_PACKAGE "g1_sdk")
set(g1_sdk_VERSION "0.0.0")
set(g1_sdk_MAINTAINER "Robot Training Academy Inc. <robottrainingacademy@gmail.com>")
set(g1_sdk_PACKAGE_FORMAT "1")
set(g1_sdk_BUILD_DEPENDS )
set(g1_sdk_BUILD_EXPORT_DEPENDS "g1_demos" "g1_vision" "g1_control")
set(g1_sdk_BUILDTOOL_DEPENDS "catkin")
set(g1_sdk_BUILDTOOL_EXPORT_DEPENDS )
set(g1_sdk_EXEC_DEPENDS "g1_demos" "g1_vision" "g1_control")
set(g1_sdk_RUN_DEPENDS "g1_demos" "g1_vision" "g1_control")
set(g1_sdk_TEST_DEPENDS )
set(g1_sdk_DOC_DEPENDS )
set(g1_sdk_DEPRECATED "")