# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/AnalogIOState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/AnalogIOStates.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/AnalogOutputCommand.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/AssemblyState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/AssemblyStates.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/CameraControl.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/CameraSettings.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/CollisionAvoidanceState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/CollisionDetectionState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/DigitalIOState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/DigitalIOStates.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/DigitalOutputCommand.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/EndEffectorCommand.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/EndEffectorProperties.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/EndEffectorState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/EndpointState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/EndpointStates.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/HeadPanCommand.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/HeadState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/JointCommand.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/NavigatorState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/NavigatorStates.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/RobustControllerStatus.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/SEAJointState.msg;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg/URDFConfiguration.msg"
services_str = "/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/srv/CloseCamera.srv;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/srv/ListCameras.srv;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/srv/OpenCamera.srv;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/srv/SolvePositionIK.srv"
pkg_name = "baxter_core_msgs"
dependencies_str = "geometry_msgs;sensor_msgs;std_msgs"
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "baxter_core_msgs;/home/arc/ros_ws/src/baxter_common/baxter_core_msgs/msg;geometry_msgs;/opt/ros/indigo/share/geometry_msgs/cmake/../msg;sensor_msgs;/opt/ros/indigo/share/sensor_msgs/cmake/../msg;std_msgs;/opt/ros/indigo/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/indigo/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
