set(_CATKIN_CURRENT_PACKAGE "arcbaxter")
set(arcbaxter_VERSION "0.0.0")
set(arcbaxter_MAINTAINER "baxterumd <baxterumd@todo.todo>")
set(arcbaxter_PACKAGE_FORMAT "1")
set(arcbaxter_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(arcbaxter_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(arcbaxter_BUILDTOOL_DEPENDS "catkin")
set(arcbaxter_BUILDTOOL_EXPORT_DEPENDS )
set(arcbaxter_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(arcbaxter_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(arcbaxter_TEST_DEPENDS )
set(arcbaxter_DOC_DEPENDS )
set(arcbaxter_DEPRECATED "")